http:
  routers:
    # --- Роутер для подписок  ---
    router-ru-subscription:
      rule: "Host(`<ВАШ_ДОМЕН_3XUI>`) && PathPrefix(`/sub`)"
      entryPoints: ["websecure"]
      service: service-ru-subscription
      priority: 10 # Приоритет выше, чем у панели
      tls: { certResolver: "letsencrypt" }

    # --- Роутер для панели  ---
    router-ru-panel:
      rule: "Host(`<ВАШ_ДОМЕН_3XUI>`)"
      entryPoints: ["websecure"]
      service: service-ru-panel
      priority: 1 # Низкий приоритет
      tls: { certResolver: "letsencrypt" }


  services:
    service-ru-subscription:
      loadBalancer:
        servers:
          # ВАЖНО: Указываем HTTPS и отключаем проверку сертификата
          - url: "https://<IP_СЕРВЕРА>:2096"
        serverstransport: "transport-insecure" # Используем общий транспорт

    service-ru-panel:
      loadBalancer:
        servers:
          # ВАЖНО: Указываем HTTPS и отключаем проверку сертификата
          - url: "https://<IP_СЕРВЕРА>:ПОРТ"
        serverstransport: "transport-insecure" # Используем общий транспорт

    # --- Добавьте здесь аналогичные сервисы для ftp и ai ---

  # --- Общий транспорт для всех сервисов, чтобы не дублировать код ---
  serversTransports:
    transport-insecure:
      insecureSkipVerify: true # Отключаем проверку SSL для всех